### ISSUE TITLE
AttributeError: 'EcoVentFan' object has no attribute '_unit_type'

### ISSUE THREAD

**Issue by euinor** [49jan/hass-ecovent#10]
I'm getting the below error with ver 1.3. The fan entity is created but unavailable.
```
Logger: homeassistant.components.fan
Source: custom_components/ecovent/fan.py:1123
Integration: Fan (documentation, issues)
First occurred: 4 January 2023 at 22:46:42 (2 occurrences)
Last logged: 4 January 2023 at 22:46:43

Error adding entities for domain fan with platform ecovent
Error while setting up ecovent platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 586, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/ecovent/fan.py", line 400, in extra_state_attributes
    data[ATTR_UNIT_TYPE] = self.unit_type
  File "/config/custom_components/ecovent/fan.py", line 1123, in unit_type
    return self._unit_type
AttributeError: 'EcoVentFan' object has no attribute '_unit_type'
```

This is my config
```
fan:
  - platform: ecovent
    name: Master Bedroom dMVHR 
    ip_address: " 192.168.0.22" 
    device_id: "002E002642435713"
```

**Comment by jreidel** [comment]
Similiar error. I think I have a v1 TwinFresh fan, maybe it's not supported? What kind of fan do you have @euinor ?

**Comment by euinor** [comment]
It is a Blauberg VENTO EXPERT A50-1 S10 W V.2. The A50 is not explicitly supported but it should be the same as the supported Blauberg fans. I do have an A30 and an A30 DUO so maybe I'll try those.

**Comment by 49jan** [comment]
What version of HA are you using?

**Comment by euinor** [comment]
This is with 2023.1.0

**Comment by yarosman** [comment]
Have same issues with A100 on 2023.3.5

**Comment by kondrikserg** [comment]
And i have similar error with _unit_type

**Comment by archipita** [comment]
I am trying to use this extension as well and I have the same error with _unite_type_.
Commenting out this line in fan.py, I get the error on the next parameter (_airflow_).
The first two are working (_airflows_ and _id_).
Can it be that there are changes with the parameters' names?
My HA is 2023.11.6 and the integration is v1.3.

**Comment by MrOzzOnline** [comment]
same issue here

AttributeError: 'EcoVentFan' object has no attribute '_unit_type'
2023-12-04 17:46:57.819 ERROR (MainThread) [homeassistant.components.fan] Error while setting up ecovent platform for fan
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
state, attr = self._async_generate_attributes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 787, in _async_generate_attributes
attr.update(self.extra_state_attributes or {})
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ecovent/fan.py", line 400, in extra_state_attributes
data[ATTR_UNIT_TYPE] = self.unit_type
^^^^^^^^^^^^^^
File "/config/custom_components/ecovent/fan.py", line 1123, in unit_type
return self._unit_type

**Comment by awisur** [comment]
Same issue still, just got two of theese installed. Please fix =)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1002, in __async_calculate_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent/fan.py", line 400, in extra_state_attributes
    data[ATTR_UNIT_TYPE] = self.unit_type
                           ^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent/fan.py", line 1123, in unit_type
    return self._unit_type
           ^^^^^^^^^^^^^^^
AttributeError: 'EcoVentFan' object has no attribute '_unit_type'

**Comment by sergt1978** [comment]
I also have attribute errors, the Winzel Expert WiFi RW1-50 P model is a complete analog, as I understand it, of the Blauberg Vento Expert A50-1 W

Эта ошибка возникла в пользовательской интеграции.

Регистратор: homeassistant
Источник: custom_components/ecovent/fan.py:1149
интеграция: Eco Heat Recovery Ventilation (документация, проблемы)
Зафиксировано первый раз: 22:04:45 (1 случай)
Зафиксировано последний раз: 22:04:45

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1130, in _async_update_entity_states
    await entity.async_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 981, in async_update_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1151, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1092, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent/fan.py", line 405, in extra_state_attributes
    data[ATTR_UNIT_TYPE] = self.unit_type
                           ^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent/fan.py", line 1149, in unit_type
    return self._unit_type
           ^^^^^^^^^^^^^^^
AttributeError: 'EcoVentFan' object has no attribute '_unit_type'. Did you mean: 'unit_type'?

**Comment by 49jan** [comment]
Hi,

A new Beta version (v1.5-beta) has just been released, which most likely resolves the issue you mentioned.
Please update to this version and check if the problem is fixed:
👉 https://github.com/49jan/hass-ecovent/releases/tag/1.5-beta

Thanks for your feedback and for helping improve the integration!
