### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by sergt1978** [49jan/hass-ecovent#3]
good afternoon, could you see why home assistant writes that integration is not supported or removed, although according to the documentation, the package structure is the same that you have in the integration as in my Winzel Expert WiFi RW1-50 P recuperator, there is a full description on the tea, please see it Рекуператор для квартиры Winzel - чистый воздух в Вашем доме Москва

**Comment by sergt1978** [comment]
https://winzel.ru/img/passport3.pdf

**Comment by 49jan** [comment]
Sorry, I don't understand the attached document because it's not in English. 

Is it perhaps a problem that you use the old version of the integration with HA 2022.4 or newer? If yes, then please check this [link](https://github.com/49jan/hass-ecovent/issues/1)

**Comment by sergt1978** [comment]
My version 2022.5.5-- С уважением,Янышев Сергей Владимировичт.с. 9-982-928-02-43т.с. 8-908-859-21-9825.05.2022, 19:48, "49jan" ***@***.***>:
Sorry, I don't understand the attached document because it's not in English.
Is it perhaps a problem that you use the old version of the integration with HA 2022.4 or newer? If yes, then please check this link

**Comment by sergt1978** [comment]
such a file translation will not help ?-- С уважением,Янышев Сергей Владимировичт.с. 9-982-928-02-43т.с. 8-908-859-21-98   25.05.2022, 19:48, "49jan" ***@***.***>: Sorry, I don't understand the attached document because it's not in English.Is it perhaps a problem that you use the old version of the integration with HA 2022.4 or newer? If yes, then please check this link—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by 49jan** [comment]
Update the hass-ecovent to version 1.1

**Comment by sergt1978** [comment]
After upgrading to version 1.1, it still doesn't work -- С уважением,Янышев Сергей Владимировичт.с. 9-982-928-02-43т.с. 8-908-859-21-98   25.05.2022, 20:41, "49jan" ***@***.***>: Update the hass-ecovent to version 1.1—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sergt1978** [comment]
Tell me what to do with the hosts.json file?Also, where to register the configuration of the ventilator in my configuration or in the custom_components - ecovent folder (configuration.yaml) ? -- С уважением,Янышев Сергей Владимировичт.с. 9-982-928-02-43т.с. 8-908-859-21-98   25.05.2022, 20:41, "49jan" ***@***.***>: Update the hass-ecovent to version 1.1—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sergt1978** [comment]
Update the hass-ecovent to version 1.1 - окHACS version - 1.25.2HA version - Home Assistant Core 2022.6.0b2 I've updated everything I can. I attach screenshots of configs, but there is still no support. Any other thoughts ?Do I need to configure configuration.yml and services files.yml in the coustom_components folder? -- С уважением,Янышев Сергей Владимировичт.с. 9-982-928-02-43т.с. 8-908-859-21-98   25.05.2022, 20:41, "49jan" ***@***.***>: Update the hass-ecovent to version 1.1—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by 49jan** [comment]
It is possible that your fan has a different interface. Let’s try to get through the basics to see where the problem is and if it will be possible to connect your fan through this integration:

1. Is your fan connected to the local network?
2. Is it possible to use it via a mobile application?
3. What is the IP, port, and password of your fan?
4. Send the configuration from configuration.yml for your fan

**Comment by sergt1978** [comment]
1. yes it works2. yes it works3. 192.168.0.3, 192.168.0.4, 192.168.0.5, Master device port – 4000; The default password is 1111.4. /config/fans.yaml   - platform: ecovent    name: Спальня сынки    ip_address: "192.168.0.3"    port: 4000    password: 1111      - platform: ecovent    name: Спальня мамы и папы    ip_address: "192.168.0.4"    port: 4000    password: 1111      - platform: ecovent    name: Спальня доченьки    ip_address: 192.168.0.5    port: 4000    password: 1111 I didn't prescribe any other settings anywhere. only in /config/fans.yaml-- С уважением,Янышев Сергей Владимировичт.с. 9-982-928-02-43т.с. 8-908-859-21-98   30.05.2022, 19:47, "49jan" ***@***.***>: It is possible that your fan has a different interface. Let’s try to get through the basics to see where the problem is and if it will be possible to connect your fan through this integration:Is your fan connected to the local network?Is it possible to use it via a mobile application?What is the IP, port, and password of your fan?Send the configuration from configuration.yml for your fan—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by 49jan** [comment]
I would ask if you can reply via the Github portal because the replies via email are very unreadable (especially configs).

1. I will therefore ask you if you can once again attach the config via Github
2. Verify if after HA restart exists HA log with the text "Created EcoVent fan controller..." 
3. Check if there is an error in the HA log related to EcoVent integration. If you have anything please send me to check what the problem is.

**Comment by sergt1978** [comment]
good evening -- С уважением,Янышев Сергей Владимировичт.с. 9-982-928-02-43т.с. 8-908-859-21-98   03.06.2022, 22:46, "49jan" ***@***.***>: I would ask if you can reply via the Github portal because the replies via email are very unreadable (especially configs and others).I will therefore ask you if you can once again attach the config via GithubVerify if after HA restart exists HA log with the text "Created EcoVent fan controller..."Check if there is an error in the HA log related to EcoVent integration. If you have anything please send me to check what the problem is.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sergt1978** [comment]
Dear friend? that's all I have on the setup and the ecovent setup log.I just would like to at least make a start/stop my fans. Since when the air conditioner is turned on, it is better that they do not work, and for this I would like to set up automation.   -- С уважением,Янышев Сергей Владимировичт.с. 9-982-928-02-43т.с. 8-908-859-21-98   03.06.2022, 22:46, "49jan" ***@***.***>: I would ask if you can reply via the Github portal because the replies via email are very unreadable (especially configs and others).I will therefore ask you if you can once again attach the config via GithubVerify if after HA restart exists HA log with the text "Created EcoVent fan controller..."Check if there is an error in the HA log related to EcoVent integration. If you have anything please send me to check what the problem is.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sergt1978** [comment]
good afternoon, and if I ask you to finalize your integration to work with my devices for an additional fee, will you agree? and for what amount? -- С уважением,Янышев Сергей Владимировичт.с. 9-982-928-02-43т.с. 8-908-859-21-98   03.06.2022, 22:46, "49jan" ***@***.***>: I would ask if you can reply via the Github portal because the replies via email are very unreadable (especially configs and others).I will therefore ask you if you can once again attach the config via GithubVerify if after HA restart exists HA log with the text "Created EcoVent fan controller..."Check if there is an error in the HA log related to EcoVent integration. If you have anything please send me to check what the problem is.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sergt1978** [comment]
- platform: ecovent
    ip_address: 192.168.0.3

  - platform: ecovent
    ip_address: 192.168.0.4

  - platform: ecovent
    ip_address: 192.168.0.5

**Comment by sergt1978** [comment]
2022-08-22 21:44:39.841 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ecovent which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-22 21:45:04.658 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform ecovent is taking over 10 seconds.
2022-08-22 21:45:04.857 ERROR (MainThread) [homeassistant.components.fan] Error while setting up ecovent platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ecovent/fan.py", line 77, in async_setup_platform
    fan = EcoVentFan(
  File "/config/custom_components/ecovent/fan.py", line 270, in __init__
    self._id = self.device_search
  File "/config/custom_components/ecovent/fan.py", line 935, in device_search
    return self._device_search
AttributeError: 'EcoVentFan' object has no attribute '_device_search'

**Comment by sergt1978** [comment]
2022-08-22 21:45:09.257 ERROR (MainThread) [homeassistant.components.fan] Error adding entities for domain fan with platform ecovent
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 775, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/ecovent/fan.py", line 287, in async_added_to_hass
    self.state,
  File "/config/custom_components/ecovent/fan.py", line 705, in state
    return self._state
AttributeError: 'EcoVentFan' object has no attribute '_state'
2022-08-22 21:45:09.500 ERROR (MainThread) [homeassistant.components.fan] Error while setting up ecovent platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 775, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/ecovent/fan.py", line 287, in async_added_to_hass
    self.state,
  File "/config/custom_components/ecovent/fan.py", line 705, in state
    return self._state
AttributeError: 'EcoVentFan' object has no attribute '_state'

**Comment by sergt1978** [comment]
Let's check if I did everything right: 1. Install the 49jan/hass-ecovent custom repository. 2. Install EcoVent integration;3. Restart HA. 4. make settings in the Fan section:     - platform: ecoventname: Sonny's bedroom    ip_address: "192.168.0.3"4. Reboot HA.Is that all? Or what did I not do or miss ? -- С уважением,Янышев Сергей Владимировичт.с. 9-982-928-02-43т.с. 8-908-859-21-98   03.06.2022, 22:46, "49jan" ***@***.***>: I would ask if you can reply via the Github portal because the replies via email are very unreadable (especially configs and others).I will therefore ask you if you can once again attach the config via GithubVerify if after HA restart exists HA log with the text "Created EcoVent fan controller..."Check if there is an error in the HA log related to EcoVent integration. If you have anything please send me to check what the problem is.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sergt1978** [comment]
Good afternoon? Did I create everything from the beginning? first, I deleted everything and created it with this configuration as in the picture, there was an error adding objects in the log.  -- С уважением,Янышев Сергей Владимировичт.с. 9-982-928-02-43т.с. 8-908-859-21-98   03.06.2022, 22:46, "49jan" ***@***.***>: I would ask if you can reply via the Github portal because the replies via email are very unreadable (especially configs and others).I will therefore ask you if you can once again attach the config via GithubVerify if after HA restart exists HA log with the text "Created EcoVent fan controller..."Check if there is an error in the HA log related to EcoVent integration. If you have anything please send me to check what the problem is.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sergt1978** [comment]
Thank you very much , I will test it now -- С уважением,Янышев Сергей Владимировичт.с. 9-982-928-02-43т.с. 8-908-859-21-98   25.05.2022, 20:41, "49jan" ***@***.***>: Update the hass-ecovent to version 1.1—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sergt1978** [comment]
additional photos -- С уважением,Янышев Сергей Владимировичт.с. 9-982-928-02-43т.с. 8-908-859-21-98   30.05.2022, 19:47, "49jan" ***@***.***>: It is possible that your fan has a different interface. Let’s try to get through the basics to see where the problem is and if it will be possible to connect your fan through this integration:Is your fan connected to the local network?Is it possible to use it via a mobile application?What is the IP, port, and password of your fan?Send the configuration from configuration.yml for your fan—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by 49jan** [comment]
I didn't get the attached pictures. As I already wrote in one of the comments above, please write comments via link: [github.com/49jan/hass-ecovent/issues/3](https://github.com/49jan/hass-ecovent/issues/3)

Some issues are already fixed on the main branch. Try to Redownload integration over HACS and select version **main**:
![image](https://user-images.githubusercontent.com/96956907/195122376-099b6a63-8b9f-43f9-beca-b69a75c7484c.png)



I guess the error in the last attached log is something about the HA version. Which Home Assistant Core do you have?

**Comment by sergt1978** [comment]
![Снимок21](https://user-images.githubusercontent.com/93818054/195128963-c8df259b-4865-42e7-a394-3d9c5c5469e4.JPG)
![Screenshot_20221011-195708](https://user-images.githubusercontent.com/93818054/195128974-50c5298f-230d-4854-850a-b3a68da49c44.jpg)
![Screenshot_20221011-195727](https://user-images.githubusercontent.com/93818054/195128985-c0f05343-c329-415e-b38a-4828a7fa067b.jpg)
![Снимок22](https://user-images.githubusercontent.com/93818054/195128989-8f0696f1-2be6-4560-a196-999b78024a86.JPG)
![Снимок20](https://user-images.githubusercontent.com/93818054/195128993-fd65c42c-da09-4494-b1b0-2f1f4e97dff8.JPG)

I attach screenshots of the settings. Everything is controlled from the mobile application, only one fan is defined in hass.

**Comment by sergt1978** [comment]
why should I choose the main version? if version 1.5 is available today?

**Comment by 49jan** [comment]
The current latest release is 1.2b (beta). But on the main, there are already some new fixes.

Are all 4 fans the same? If one is working and the other 3 not, there has to be something wrong with the configuration. I suggest that you remove device_id from the configuration (at least for fan_04, fan_05, and fan_06) and check if it will work.
